### ISSUE TITLE
Create resources directory

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-segmentation-evaluation#4]
# User story
Create a resources directory to store examples and initializations

# Acceptance criteria
- [x] files in demo.py should be inside resources dir instead of local path
- [x] clear organization between examples/tests

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by anna-grim** [comment]
Issue is addressed in the current pull request
