### ISSUE TITLE
Add linters

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-segmentation-evaluation#5]
# User story
As a developer, I want to run linters on github actions to ensure the code is readable, maintainable, and more consistent.

# Acceptance criteria
- [x] Run flake8 . and fix all issues (ex: replace star imports)
- [x] uncomment lint in ci.yml
- [x] add docstrings and change interrogate fail to 100

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by anna-grim** [comment]
Issues is resolved in current pull request
